### ISSUE TITLE
How to Integrate android-libjpeg-turbo to my project in android studio.

### ISSUE THREAD

**Issue by amarpulli1994** [openstf/android-libjpeg-turbo#10]
Hello all,
This is the my new step to integrate android-libjpeg-turbo to my android project.
Can any one please teach me how to integrate android-libjpeg-turbo.
I searched so many articles but no luck, didn't get any correct answer.
I did that just downloading the android-libjpeg-turbo repository.
Don't know how to proceed with that.
Please guide me to work with android-libjpeg-turbo.

System Specifications:
Android Tool : Android Studio.2.3.3.
Java version:  Java 1.8
Operating System: Windows 10 (64 bit).

**Comment by sorccu** [comment]
No, if I did that I would have no time for anything else. Your question is far too time consuming, you should try to figure out things by yourself and only ask when when you have a very specific issue. We just provide the software, that's all. Perhaps you can look at minicap as an example.
