### ISSUE TITLE
build-binary.mk:464: *** multiple target patterns.  Stop.

### ISSUE THREAD

**Issue by tingfengainiaini** [openstf/android-libjpeg-turbo#2]
I can not run ndk-build with this error. Do you know what this error mean ?

**Comment by tingfengainiaini** [comment]
I have fixed it. It is my 'make' version error.

**Comment by Jia-HongHenryLee** [comment]
Hello. Nice to meet you. 
I have the same problem, but I don't know how to solve it.
![capture](https://cloud.githubusercontent.com/assets/18475235/17320409/01e90c2a-58c6-11e6-938f-dfec4529ce2e.PNG)
May I ask you how to solve it?
Thank you for your help.
