### ISSUE TITLE
error: undefined reference to 'jconst_huff_encode_one_block'

### ISSUE THREAD

**Issue by RVPLiu** [openstf/android-libjpeg-turbo#6]
hi, I upgrade lib version to the newest version 1.5.2, and when I build the shared library in x86, I came to this error:

```
...
...
Library/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/darwin-x86_64/lib/gcc/i686-linux-android/4.9.x/../../../../i686-linux-android/bin/ld: warning: shared library text segment is not shareable

jni/libjpeg/libjpeg-turbo-1.5.2/simd/jsimd_i386.c:1077: error: undefined reference to 'jconst_huff_encode_one_block'

jni/libjpeg/libjpeg-turbo-1.5.2/simd/jsimd_i386.c:1089: error: undefined reference to 'jsimd_huff_encode_one_block_sse2'
```

Hope for your response!

**Comment by sorccu** [comment]
Sounds like there are new files that need to be compiled. You have to
modify the .mk to include the new files.

**Comment by RVPLiu** [comment]
yes, that's it.  jchuff-sse2.asm file was added in the newest version(1.5.2). thanks for your great help.
